name: Continuous Integration/Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Verify code formatting
        run: go fmt ./...

      - name: Verify linting
        run: go vet ./...
