name: Continuous Integration/Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Verify code formatting
        run: go fmt ./...

      - name: Verify linting
        run: go vet ./...

  release-cycle:
    needs:
      - commit-cycle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
