name: Continuous Integration/Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commit-cycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Verify code formatting
        run: go fmt ./...

      - name: Verify linting
        run: go vet ./...

  release-cycle:
    needs:
      - commit-cycle
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and create tag
        id: version_tag
        run: |
          TAG_NAME="v0.1.0"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            your-binary-file  # Replace with the actual binary or release assets
          token: ${{ secrets.GITHUB_TOKEN }}
          release_tag: ${{ steps.version_tag.outputs.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the release ID
        run: echo "Release ID: ${{ steps.create_release.outputs.id }}"